<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2016/05/05 12:42:52
sfConfig::add(array(
  'mod_funcionario_cargo_certificado_enabled' => true,
  'mod_funcionario_cargo_certificado_view_class' => 'sfPHP',
));
