<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/05/14 23:09:36

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=prueba-SIGLAS',
  'username' => 'u_siglas',
  'password' => 's1gl4s919',
  'name' => 'doctrine',
)),);
