<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/05/05 12:53:37

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=10.2.201.110;dbname=prueba-SIGLAS',
  'username' => 'u_siglas',
  'password' => 's1gl4s919',
  'name' => 'doctrine',
)),);
