<?php
// This a cache config file for the sfTCPDFPlugin 
//
// auto-generated by sfTCPDFPluginConfigHandler
// date: 2016/05/05 14:13:41
return array (
  'default' => 
  array (
    'K_TCPDF_EXTERNAL_CONFIG' => true,
    'K_PATH_MAIN' => '/var/www/html/siglas-mppp/plugins/sfTCPDFPlugin/lib/tcpdf/',
    'K_PATH_URL' => 'http://sc.mppp.gob.ve/',
    'K_PATH_FONTS' => '/var/www/html/siglas-mppp/plugins/sfTCPDFPlugin/lib/tcpdf/fonts/',
    'K_PATH_CACHE' => '/var/www/html/siglas-mppp/plugins/sfTCPDFPlugin/tcpdf/lib/cache/',
    'K_PATH_URL_CACHE' => 'http://sc.mppp.gob.ve/cache/',
    'K_PATH_IMAGES' => '/var/www/html/siglas-mppp/web/images/organismo/pdf/',
    'K_BLANK_IMAGE' => '/var/www/html/siglas-mppp/plugins/sfTCPDFPlugin/tcpdf/images/_blank.png',
    'PDF_PAGE_FORMAT' => 'LETTER',
    'PDF_PAGE_ORIENTATION' => 'P',
    'PDF_HEADER_TITLE' => '',
    'PDF_HEADER_STRING' => '',
    'PDF_HEADER_LOGO' => 'gob_pdf.png',
    'PDF_HEADER_LOGO_WIDTH' => 450,
    'PDF_UNIT' => 'pt',
    'PDF_MARGIN_HEADER' => '0',
    'PDF_MARGIN_FOOTER' => '0',
    'PDF_MARGIN_TOP' => '80',
    'PDF_MARGIN_BOTTOM' => '25',
    'PDF_MARGIN_LEFT' => '0',
    'PDF_MARGIN_RIGHT' => '20',
    'PDF_FONT_NAME_MAIN' => 'helvetica',
    'PDF_FONT_SIZE_MAIN' => '10',
    'PDF_FONT_NAME_DATA' => 'helvetica',
    'PDF_FONT_SIZE_DATA' => '8',
    'PDF_FONT_MONOSPACED' => 'courier',
    'PDF_IMAGE_SCALE_RATIO' => '4',
    'HEAD_MAGNIFICATION' => '1.1',
    'K_CELL_HEIGHT_RATIO' => '1.25',
    'K_TITLE_MAGNIFICATION' => '1.3',
    'K_SMALL_RATIO' => '2/3',
    'PDF_CREATOR' => 'TCPDF',
    'PDF_AUTHOR' => 'ProSoft Solutions Venezuela C.A. siglas.ve@gmail.com. (058)426-511.42.50',
  ),
  'my_config' => 
  array (
    'K_TCPDF_EXTERNAL_CONFIG' => true,
    'K_PATH_MAIN' => '/var/www/my-symfony-project/plugins/sfTCPDFPlugin/tcpdf/',
    'K_PATH_URL' => 'http://dev.my-symfony-project/',
    'K_PATH_FONTS' => '/var/www/my-symfony-project/plugins/sfTCPDFPlugin/tcpdf/fonts',
    'K_PATH_CACHE' => '/var/www/my-symfony-project/plugins/sfTCPDFPlugin/tcpdf/cache',
    'K_PATH_URL_CACHE' => 'http://dev.my-symfony-project/cache',
    'K_PATH_IMAGES' => '/var/www/my-symfony-project/plugins/sfTCPDFPlugin/tcpdf/images',
    'K_BLANK_IMAGE' => '/var/www/my-symfony-project/plugins/sfTCPDFPlugin/tcpdf/images/_blank.png',
  ),
);
//
